### ISSUE TITLE
Media Query Support

### ISSUE THREAD

**Issue by mhemesath** [jhildenbiddle/css-vars-ponyfill#58] opened 2019-02-21 19:34 UTC
Wondering if it's possible to honor media queries when outputting CSS. For example:

```css
@media only screen and (max-width: 600px) {
  :root {
    --color: red;
  }

  .foo {
    color: var(--color);
  }
}
```

would output
```html
<style>
@media only screen and (max-width: 600px) {
  .foo {
    color: red;
  }
}
</style>
```

**Comment by jhildenbiddle** [comment] 2019-02-22 06:55
Duplicate of #31 (which was closed but added to the backlog, but I have since reopened it for better visibility).

Quick recap: It should be possible, although it is unlikely that I will have time to dive into this anytime soon

Thanks for your interest, @mhemesath.

**Closed by jhildenbiddle** 2019-02-22 06:55 UTC
